"""ok

Revision ID: 3f69904f60e3
Revises: 
Create Date: 2019-01-18 16:15:42.118658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f69904f60e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screenings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movies_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=5), nullable=True),
    sa.Column('day', sa.String(length=2), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movies_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('seat_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('costumer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screenings_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('card_number', sa.Integer(), nullable=True),
    sa.Column('card_code', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('number_of_seats', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['screenings_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seat_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seats_id', sa.Integer(), nullable=True),
    sa.Column('rooms_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('screenings_id', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['costumer.id'], ),
    sa.ForeignKeyConstraint(['rooms_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['screenings_id'], ['screenings.id'], ),
    sa.ForeignKeyConstraint(['seats_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seat_reservation')
    op.drop_table('costumer')
    op.drop_table('seats')
    op.drop_table('screenings')
    op.drop_table('rooms')
    op.drop_table('movies')
    # ### end Alembic commands ###
