"""empty message

Revision ID: d1049e656c7b
Revises: 3f69904f60e3
Create Date: 2019-01-21 12:04:46.871895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1049e656c7b'
down_revision = '3f69904f60e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('Day', sa.String(length=2), nullable=True))
    op.drop_column('screenings', 'day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('day', sa.VARCHAR(length=20), nullable=True))
    op.drop_column('screenings', 'Day')
    # ### end Alembic commands ###
